

run:
	echo Riccardo see this on: http://localhost:1313/
	hugo server -D
	git submodule add https://github.com/google/docsy.git themes/docsy-submodule/
	#echo 'theme = "docsy"' >> config.toml
	git submodule update --init --recursive


server: run